[workspace]
resolver = "2"

members = ["nes-base", "nes-cpu", "nes-ram", "nes-bus", "nes-board", "nes-cartridge", "nes-dma"]

[profile.release]
opt-level = "s"

[profile.dev]
debug = true
opt-level = "z"
